WRITE TEST PATTERN TO DRUM TRACK 8, 010
/ The few implemented PDP1-D instructions
lia=760020
lai=760040
lsw=760060

/ This defines the IOT instructions for the Type 23 drum.
/ Note this differs from the examples in that it does not add the iot
/ explicitly, so use is e.g. iot dia.
dia=61
dba=2061
dwc=62
dra=2062
dcl=63
dss=2063

/ Additional flags, not compatible with native macro, only macro1.
/ These flags are in the IO register.
drmrd=400000
drmwrt=400000

/ Bits for dss
drms16=40
drmsch=20

/ The bit set if a cks is done.
cksdrm=1


/ Which bank we load the track image into, 1
bnk=10000
bnkno=1
100/

/ load bank 1 mem from drum 010
     lio (drmrd 100000
     iot dia
     cli
     iot dwc
     lio (10000
     iot dcl

/ use cpy to copy 0-10 to 100-110
     eem
     lac (10000
     dac ads
     lac (10100
     dac adt
     law 10
     jda cpy
     hlt

/ Copy from one mem bank to another.
/ AC has the count of words to copy.
/ Location ads has the location in the source bank to copy from.
/ Location adt has the destination.
/ Both can have extended addresses.
/ If extended addresses are used, be sure an eem has been done first.
cpy, 0
    dap cd
    lac cpy
    cma
cl, add (1
    lsw
    lac i ads
    dac i adt
    idx ads
    idx adt
    lsw
    sza
    jmp cl
cd, jmp .
ads, 0
adt, 0

constants
start 100
