#!/bin/bash
# flow_check.sh -- acceptance check for the am1 optimizer's control-flow
# overlay (task A4).  Task A6 adopts it into the Tests/Optimizer suite.
#
# Four checks:
#   1. "am1 -O=flow" on flow_test.am1 must equal flow_test.expected line for
#      line.  The expected file was written by hand from the task's rules and
#      the study's section 5.4, not generated by the analysis, so a difference
#      means one of the two is wrong and somebody has to look.  The report
#      written beside it must count the same blocks and the same unreached
#      words the expected file shows.
#   2. For every assemblable test in the regression suite, the flow dump's
#      word section must have exactly the lines the -O=dump word table has,
#      with the same address and value columns: the overlay covers every word
#      the table holds and invents none.
#   3. Every block line must be well formed, every word that carries a block
#      id must appear inside that block's address range, and no word outside
#      the graph may carry one.  This is what catches an edge that lands in
#      the middle of a block, which would silently break precondition P1.
#   4. The analysis must be deterministic: two runs on the same source give
#      the same dump.
#
# Usage: flow_check.sh [am1] [regression-dir]
#   am1             the am1 to test, default ../../am1 relative to this script
#   regression-dir  where the rgNN tests live, default Tools/AM1/Tests/Regression
#
# On this machine it runs under WSL bash.  Exit status 0 when everything
# passes, 1 otherwise.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AM1="${1:-"$SCRIPT_DIR/../../am1"}"
REG="${2:-"$SCRIPT_DIR/../../../../Tools/AM1/Tests/Regression"}"

if [ ! -x "$AM1" ]; then
    echo "am1 binary not found or not executable: $AM1"
    exit 1
fi

if [ ! -d "$REG" ]; then
    echo "regression directory not found: $REG"
    exit 1
fi

AM1="$(cd "$(dirname "$AM1")" && pwd)/$(basename "$AM1")"
REG="$(cd "$REG" && pwd)"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

pass=0
fail=0
FAILURES=()

# --- 1. the hand-written expectations ------------------------------------

cp "$SCRIPT_DIR/flow_test.am1" "$WORK/"
cd "$WORK" || exit 1

"$AM1" -O=flow flow_test.am1 > flow.out 2> flow.err
rc=$?
if [ $rc -ne 0 ] || [ ! -f flow_test.opt ]; then
    echo "FAIL:  flow_test (assembly with -O=flow failed, rc=$rc)"
    sed 's/^/       /' flow.err
    fail=$((fail+1)); FAILURES+=("flow_test")
elif diff -u "$SCRIPT_DIR/flow_test.expected" flow.out > flow.diff; then
    echo "PASS:  flow_test ($(wc -l < flow.out) lines equal the hand-written expectations)"
    pass=$((pass+1))
else
    echo "FAIL:  flow_test (control-flow dump differs from flow_test.expected; - expected, + analysis)"
    sed 's/^/       /' flow.diff
    fail=$((fail+1)); FAILURES+=("flow_test")
fi

if [ -s flow.err ]; then
    echo "FAIL:  flow_test (the analysis wrote to stderr)"
    sed 's/^/       /' flow.err
    fail=$((fail+1)); FAILURES+=("flow_test-stderr")
fi

# The report must agree with the dump about how many blocks there are and how
# many words nothing reaches.
expected_blocks=$(grep -c '^block ' "$SCRIPT_DIR/flow_test.expected")
expected_unreached=$(sed -n 's/^unreached: //p' "$SCRIPT_DIR/flow_test.expected" | wc -w)
if grep -q "flow: $expected_blocks blocks," flow_test.opt; then
    echo "PASS:  flow_test report counts $expected_blocks blocks"
    pass=$((pass+1))
else
    echo "FAIL:  flow_test report does not count $expected_blocks blocks"
    grep 'flow:' flow_test.opt | sed 's/^/       /'
    fail=$((fail+1)); FAILURES+=("flow_test-report")
fi

if grep -q "unreached holding $expected_unreached word" flow_test.opt; then
    echo "PASS:  flow_test report counts $expected_unreached unreached words"
    pass=$((pass+1))
else
    echo "FAIL:  flow_test report does not count $expected_unreached unreached words"
    grep 'reachability:' flow_test.opt | sed 's/^/       /'
    fail=$((fail+1)); FAILURES+=("flow_test-report")
fi

# --- 2, 3 and 4: every regression test analyzes ---------------------------

# Runs one regression source with both dumps and checks the flow dump against
# the word table and against itself.  Arguments: test name, source path, then
# any extra am1 flags.
run_one()
{
    local name=$1 src=$2
    shift 2
    local flags=("$@")
    local rc

    "$AM1" "${flags[@]}" -O=dump -I"$REG" "$src" > "$name.wt" 2> "$name.err"
    rc=$?
    if [ $rc -ne 0 ]; then
        echo "FAIL:  $name (assembly with -O=dump failed, rc=$rc)"
        sed 's/^/       /' "$name.err"
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    "$AM1" "${flags[@]}" -O=flow -I"$REG" "$src" > "$name.fl" 2> "$name.err"
    rc=$?
    if [ $rc -ne 0 ]; then
        echo "FAIL:  $name (assembly with -O=flow failed, rc=$rc)"
        sed 's/^/       /' "$name.err"
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    if grep -q 'optimizer:' "$name.err"; then
        echo "FAIL:  $name (the analysis reported something it could not place)"
        grep 'optimizer:' "$name.err" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    # Split the dump into its three parts.  Every word line carries a block
    # column, so "block " is what tells the parts apart at the start of a line.
    grep -v '^block [0-9]' "$name.fl" | grep -v '^entry set:' | grep -v '^unreached:' > "$name.words"
    grep '^block [0-9]' "$name.fl" > "$name.blocks"

    # The word section covers exactly the table, reserved words apart: a
    # reserved word has no value column and is not in the -O=dump table.
    awk '$2 != "------" { print $1, $2 }' "$name.words" > "$name.flav"
    if ! cmp -s "$name.wt" "$name.flav"; then
        echo "FAIL:  $name (flow dump's address/value columns differ from -O=dump)"
        diff "$name.wt" "$name.flav" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    # Every word line must carry a block column, "-" or an id.
    if grep -v -q ' block \(-\|[0-9]\)' "$name.words"; then
        echo "FAIL:  $name (a word line lacks a block column)"
        grep -v ' block \(-\|[0-9]\)' "$name.words" | head -5 | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    # Every block line must be well formed and every successor must name
    # either an address or a sink reason.
    if [ -s "$name.blocks" ] && grep -v -q ' words\?, [0-9]* in, ends .* | succ: ' "$name.blocks"; then
        echo "FAIL:  $name (a block line is malformed)"
        grep -v ' words\?, [0-9]* in, ends .* | succ: ' "$name.blocks" | head -5 | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    # Every word carrying a block id must lie inside that block's range, and
    # the ids a block claims must be exactly the words in its range.  This is
    # the check that would catch an edge landing mid-block.
    # FILENAME, not the usual FNR == NR: a source with no code words at all
    # (rg14_text and friends) has an EMPTY block file, and awk never reads it,
    # so FNR == NR would be true for the first line of the word file instead
    # and every word would be parsed as a block.
    if ! awk -v blocksF="$name.blocks" '
        FILENAME == blocksF {
            # block N: BBAAAA-BBAAAA W words, ...
            id = $2; sub(/:$/, "", id)
            split($3, range, "-")
            lo[id] = range[1]; hi[id] = range[2]
            words[id] = $4
            next
        }
        {
            for( i = 1; i <= NF; ++i )
            {
                if( $i == "block" ) { col = $(i + 1); break }
            }
            if( col == "-" ) next
            if( !(col in lo) ) { print "word " $1 " names block " col ", which does not exist"; bad = 1; next }
            if( $1 < lo[col] || $1 > hi[col] ) { print "word " $1 " names block " col " (" lo[col] "-" hi[col] ")"; bad = 1 }
            seen[col]++
        }
        END {
            for( id in lo )
            {
                if( seen[id] != words[id] ) { print "block " id " claims " words[id] " words, " seen[id] " words name it"; bad = 1 }
            }
            exit( (bad)?1:0 )
        }
    ' "$name.blocks" "$name.words" > "$name.ranges"; then
        echo "FAIL:  $name (a word and its block disagree)"
        head -5 "$name.ranges" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    # Determinism: a second run gives the same dump.
    "$AM1" "${flags[@]}" -O=flow -I"$REG" "$src" > "$name.fl2" 2> /dev/null
    if cmp -s "$name.fl" "$name.fl2"; then
        echo "PASS:  $name ($(wc -l < "$name.words") words, $(wc -l < "$name.blocks") blocks)"
        pass=$((pass+1))
    else
        echo "FAIL:  $name (two runs gave different control-flow dumps)"
        diff "$name.fl" "$name.fl2" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
    fi
}

# rg21 first: it writes rg21_exports.sym, which rg22 imports.  rg25 needs -M
# (a deliberate overlay) and rg26 -a (space is add).  The xfail tests do not
# assemble and have no word table to analyze.
run_one rg21_exports "$REG/rg21_exports.am1"

for src in "$REG"/rg*.am1; do
    name="$(basename "$src" .am1)"
    case "$name" in
        rg21_exports)         continue ;;
        *_xfail_*)            continue ;;
        rg25_flag_M)          run_one "$name" "$src" -M ;;
        rg26_flag_a)          run_one "$name" "$src" -a ;;
        *)                    run_one "$name" "$src" ;;
    esac
done

echo
echo "Results: $pass pass, $fail fail"
if [ $fail -ne 0 ]; then
    echo "Failed: ${FAILURES[*]}"
    exit 1
fi
exit 0
