#!/bin/bash
# decoder_check.sh -- acceptance check for the am1 optimizer's instruction
# decoder (task A2).  Task A6 adopts it into the Tests/Optimizer suite.
#
# Three checks:
#   1. "am1 -O=check" runs the decoder's built-in self-check: the operate
#      group phase-table anchors (cla cma in one word is all ones, cma then
#      cla as two words is zero, the handbook's opr 3200 example) and a set
#      of words decoded by hand.  Every check must pass.
#   2. "am1 -O=decode" on decoder_test.am1 must equal decoder_test.expected
#      line for line.  The expected file was written by hand from
#      permsyms.def and the F-15D handbook, not generated by the decoder, so
#      a difference means one of the two is wrong and somebody has to look.
#   3. For every assemblable test in the regression suite, the decoded dump's
#      address and value columns (reserved words aside) must equal the -O=dump
#      word table: the decoder covers every word the table holds and never
#      fails on a word it has not met before.
#
# Usage: decoder_check.sh [am1] [regression-dir]
#   am1             the am1 to test, default ../../am1 relative to this script
#   regression-dir  where the rgNN tests live, default Tools/AM1/Tests/Regression
#
# On this machine it runs under WSL bash.  Exit status 0 when everything
# passes, 1 otherwise.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AM1="${1:-"$SCRIPT_DIR/../../am1"}"
REG="${2:-"$SCRIPT_DIR/../../../../Tools/AM1/Tests/Regression"}"

if [ ! -x "$AM1" ]; then
    echo "am1 binary not found or not executable: $AM1"
    exit 1
fi

if [ ! -d "$REG" ]; then
    echo "regression directory not found: $REG"
    exit 1
fi

AM1="$(cd "$(dirname "$AM1")" && pwd)/$(basename "$AM1")"
REG="$(cd "$REG" && pwd)"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

pass=0
fail=0
FAILURES=()

# --- 1. the self-check ---------------------------------------------------

cp "$SCRIPT_DIR/decoder_test.am1" "$WORK/"
cd "$WORK" || exit 1

"$AM1" -O=check decoder_test.am1 > check.out 2> check.err
rc=$?
summary="$(grep '^decoder self-check:' check.out)"
if [ $rc -eq 0 ] && [ -n "$summary" ] && ! grep -q '^  FAIL' check.out && [ -f decoder_test.opt ]; then
    echo "PASS:  self-check ($summary)"
    pass=$((pass+1))
else
    echo "FAIL:  self-check (rc=$rc)"
    sed 's/^/       /' check.out check.err
    fail=$((fail+1)); FAILURES+=("self-check")
fi

# --- 2. the hand-written expectations ------------------------------------

rm -f decoder_test.opt
"$AM1" -O=decode decoder_test.am1 > decode.out 2> decode.err
rc=$?
if [ $rc -ne 0 ] || [ ! -f decoder_test.opt ]; then
    echo "FAIL:  decoder_test (assembly with -O=decode failed, rc=$rc)"
    sed 's/^/       /' decode.err
    fail=$((fail+1)); FAILURES+=("decoder_test")
elif diff -u "$SCRIPT_DIR/decoder_test.expected" decode.out > decode.diff; then
    echo "PASS:  decoder_test ($(wc -l < decode.out) lines equal the hand-written expectations)"
    pass=$((pass+1))
else
    echo "FAIL:  decoder_test (decoded dump differs from decoder_test.expected; - expected, + decoder)"
    sed 's/^/       /' decode.diff
    fail=$((fail+1)); FAILURES+=("decoder_test")
fi

# --- 3. every regression test decodes, and the dumps agree ---------------

# Runs one regression source with both dumps and compares the address/value
# columns.  Arguments: test name, source path, then any extra am1 flags.
run_one()
{
    local name=$1 src=$2
    shift 2
    local flags=("$@")
    local rc

    "$AM1" "${flags[@]}" -O=dump -I"$REG" "$src" > "$name.wt" 2> "$name.err"
    rc=$?
    if [ $rc -ne 0 ]; then
        echo "FAIL:  $name (assembly with -O=dump failed, rc=$rc)"
        sed 's/^/       /' "$name.err"
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    "$AM1" "${flags[@]}" -O=decode -I"$REG" "$src" > "$name.dc" 2> "$name.err"
    rc=$?
    if [ $rc -ne 0 ]; then
        echo "FAIL:  $name (assembly with -O=decode failed, rc=$rc)"
        sed 's/^/       /' "$name.err"
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    # Every decoded line must carry a group text and a spelling; a reserved
    # word has no value column and is not in the -O=dump table.
    if grep -v -q ' | ' "$name.dc"; then
        echo "FAIL:  $name (a decoded line has no spelling column)"
        grep -v ' | ' "$name.dc" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    awk '$2 != "------" { print $1, $2 }' "$name.dc" > "$name.dcav"
    if cmp -s "$name.wt" "$name.dcav"; then
        echo "PASS:  $name ($(wc -l < "$name.dc") words decoded)"
        pass=$((pass+1))
    else
        echo "FAIL:  $name (decoded dump's address/value columns differ from -O=dump)"
        diff "$name.wt" "$name.dcav" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
    fi
}

# rg21 first: it writes rg21_exports.sym, which rg22 imports.  rg25 needs -M
# (a deliberate overlay) and rg26 -a (space is add).  The xfail tests do not
# assemble and have no word table to decode.
run_one rg21_exports "$REG/rg21_exports.am1"

for src in "$REG"/rg*.am1; do
    name="$(basename "$src" .am1)"
    case "$name" in
        rg21_exports)         continue ;;
        *_xfail_*)            continue ;;
        rg25_flag_M)          run_one "$name" "$src" -M ;;
        rg26_flag_a)          run_one "$name" "$src" -a ;;
        *)                    run_one "$name" "$src" ;;
    esac
done

echo
echo "Results: $pass pass, $fail fail"
if [ $fail -ne 0 ]; then
    echo "Failed: ${FAILURES[*]}"
    exit 1
fi
exit 0
