#!/bin/bash
# refs_check.sh -- acceptance check for the am1 optimizer's reference
# analysis (task A3).  Task A6 adopts it into the Tests/Optimizer suite.
#
# Three checks:
#   1. "am1 -O=refs" on refs_test.am1 must equal refs_test.expected line for
#      line.  The expected file was written by hand from the study's role
#      table (FeasibilityStudy.md section 5.3) and the task's acceptance
#      list, not generated by the analysis, so a difference means one of the
#      two is wrong and somebody has to look.  The report written beside it
#      must count the four conflicts the expected file shows.
#   2. For every assemblable test in the regression suite, the reference
#      dump's address and value columns must equal the -O=dump word table,
#      every line must carry both edge lists, and the analysis must not
#      report an unresolved reference: it covers every word the table holds
#      and never fails on a word it has not met before.
#   3. The analysis must be deterministic: two runs on the same source give
#      the same dump.
#
# Usage: refs_check.sh [am1] [regression-dir]
#   am1             the am1 to test, default ../../am1 relative to this script
#   regression-dir  where the rgNN tests live, default Tools/AM1/Tests/Regression
#
# On this machine it runs under WSL bash.  Exit status 0 when everything
# passes, 1 otherwise.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AM1="${1:-"$SCRIPT_DIR/../../am1"}"
REG="${2:-"$SCRIPT_DIR/../../../../Tools/AM1/Tests/Regression"}"

if [ ! -x "$AM1" ]; then
    echo "am1 binary not found or not executable: $AM1"
    exit 1
fi

if [ ! -d "$REG" ]; then
    echo "regression directory not found: $REG"
    exit 1
fi

AM1="$(cd "$(dirname "$AM1")" && pwd)/$(basename "$AM1")"
REG="$(cd "$REG" && pwd)"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

pass=0
fail=0
FAILURES=()

# --- 1. the hand-written expectations ------------------------------------

cp "$SCRIPT_DIR/refs_test.am1" "$WORK/"
cd "$WORK" || exit 1

"$AM1" -O=refs refs_test.am1 > refs.out 2> refs.err
rc=$?
if [ $rc -ne 0 ] || [ ! -f refs_test.opt ]; then
    echo "FAIL:  refs_test (assembly with -O=refs failed, rc=$rc)"
    sed 's/^/       /' refs.err
    fail=$((fail+1)); FAILURES+=("refs_test")
elif diff -u "$SCRIPT_DIR/refs_test.expected" refs.out > refs.diff; then
    echo "PASS:  refs_test ($(wc -l < refs.out) lines equal the hand-written expectations)"
    pass=$((pass+1))
else
    echo "FAIL:  refs_test (reference dump differs from refs_test.expected; - expected, + analysis)"
    sed 's/^/       /' refs.diff
    fail=$((fail+1)); FAILURES+=("refs_test")
fi

if [ -s refs.err ]; then
    echo "FAIL:  refs_test (the analysis wrote to stderr)"
    sed 's/^/       /' refs.err
    fail=$((fail+1)); FAILURES+=("refs_test-stderr")
fi

expected_conflicts=$(grep -c 'conflict:' "$SCRIPT_DIR/refs_test.expected")
if grep -q "^Classification conflicts: $expected_conflicts words" refs_test.opt; then
    echo "PASS:  refs_test report counts $expected_conflicts conflicts"
    pass=$((pass+1))
else
    echo "FAIL:  refs_test report does not count $expected_conflicts conflicts"
    grep 'onflict' refs_test.opt | sed 's/^/       /'
    fail=$((fail+1)); FAILURES+=("refs_test-report")
fi

# --- 2. every regression test analyzes, and the dumps agree --------------

# Runs one regression source with both dumps and compares the address/value
# columns.  Arguments: test name, source path, then any extra am1 flags.
run_one()
{
    local name=$1 src=$2
    shift 2
    local flags=("$@")
    local rc

    "$AM1" "${flags[@]}" -O=dump -I"$REG" "$src" > "$name.wt" 2> "$name.err"
    rc=$?
    if [ $rc -ne 0 ]; then
        echo "FAIL:  $name (assembly with -O=dump failed, rc=$rc)"
        sed 's/^/       /' "$name.err"
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    "$AM1" "${flags[@]}" -O=refs -I"$REG" "$src" > "$name.rf" 2> "$name.err"
    rc=$?
    if [ $rc -ne 0 ]; then
        echo "FAIL:  $name (assembly with -O=refs failed, rc=$rc)"
        sed 's/^/       /' "$name.err"
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    if grep -q 'optimizer:' "$name.err"; then
        echo "FAIL:  $name (the analysis reported a reference it could not place)"
        grep 'optimizer:' "$name.err" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    # Every line must carry both edge lists; a reserved word has no value
    # column and is not in the -O=dump table.
    if grep -v -q ' | out: .* | in: ' "$name.rf"; then
        echo "FAIL:  $name (a reference line lacks an edge list)"
        grep -v ' | out: .* | in: ' "$name.rf" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    awk '$2 != "------" { print $1, $2 }' "$name.rf" > "$name.rfav"
    if ! cmp -s "$name.wt" "$name.rfav"; then
        echo "FAIL:  $name (reference dump's address/value columns differ from -O=dump)"
        diff "$name.wt" "$name.rfav" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
        return
    fi

    # Determinism: a second run gives the same dump.
    "$AM1" "${flags[@]}" -O=refs -I"$REG" "$src" > "$name.rf2" 2> /dev/null
    if cmp -s "$name.rf" "$name.rf2"; then
        echo "PASS:  $name ($(wc -l < "$name.rf") words, $(grep -o -- '->' "$name.rf" | wc -l) edges)"
        pass=$((pass+1))
    else
        echo "FAIL:  $name (two runs gave different reference dumps)"
        diff "$name.rf" "$name.rf2" | sed 's/^/       /'
        fail=$((fail+1)); FAILURES+=("$name")
    fi
}

# rg21 first: it writes rg21_exports.sym, which rg22 imports.  rg25 needs -M
# (a deliberate overlay) and rg26 -a (space is add).  The xfail tests do not
# assemble and have no word table to analyze.
run_one rg21_exports "$REG/rg21_exports.am1"

for src in "$REG"/rg*.am1; do
    name="$(basename "$src" .am1)"
    case "$name" in
        rg21_exports)         continue ;;
        *_xfail_*)            continue ;;
        rg25_flag_M)          run_one "$name" "$src" -M ;;
        rg26_flag_a)          run_one "$name" "$src" -a ;;
        *)                    run_one "$name" "$src" ;;
    esac
done

echo
echo "Results: $pass pass, $fail fail"
if [ $fail -ne 0 ]; then
    echo "Failed: ${FAILURES[*]}"
    exit 1
fi
exit 0
